/**
 * UI Labels Constants
 * Centralized registry for all user interface text strings.
 * Prevents hardcoding text directly in JSX files for clean structure and easy future i18n translation.
 *
 * Related: src/app/page.tsx, src/components/base/Header.tsx
 * Pattern: Unified constants file (Zero Hardcoding standard)
 */

export const LABELS = {
  COMMON: {
    HOME: 'Trang Chủ',
    PRODUCTS: 'Sản Phẩm',
    PROMOTIONS: 'Khuyến Mãi',
    CART: 'Giỏ Hàng',
    LOGIN: 'Đăng Nhập',
    LOGOUT: 'Đăng Xuất',
    REGISTER: 'Đăng Ký',
    DETAILS: 'Chi Tiết',
    BUY_NOW: 'Mua Ngay',
    ADD_TO_CART: 'Thêm vào giỏ',
    WARRANTY_POLICY: 'Chính Sách Bảo Hành',
    TERMS_OF_USE: 'Điều khoản sử dụng',
    PRIVACY_POLICY: 'Chính sách bảo mật',
    COPYRIGHT: 'Tất cả quyền được bảo lưu.',
    NO_DATA: 'Không có dữ liệu',
  },
  HERO: {
    BADGE_TEXT: 'Nâng tầm trải nghiệm!',
    TITLE_LINE_1: 'Thiết Kế Đột Phá.',
    TITLE_LINE_2: 'Công Nghệ Dẫn Đầu.',
    DESC: 'Trải nghiệm các dòng smartphone chính hãng mới nhất tích hợp công nghệ AI tối tân cùng chế độ hậu mãi cực kỳ đẳng cấp từ Sóc Mobile.',
    CTA_EXPLORE: 'Khám Phá Ngay',
  },
  SHOWCASE: {
    SHIPPING_TITLE: 'Giao Hàng Hỏa Tốc',
    SHIPPING_DESC: 'Nhận hàng chỉ trong 2 giờ tại các khu vực nội thành. Miễn phí vận chuyển cho hóa đơn từ 15 triệu.',
    GENUINE_TITLE: '100% Chính Hãng',
    GENUINE_DESC: 'Sản phẩm phân phối chính thức, nguyên seal. Đền tiền gấp 10 lần nếu phát hiện hàng giả, hàng nhái.',
    AI_TITLE: 'Trợ Lý AI So Sánh',
    AI_DESC: 'Hệ thống so sánh thông số cấu hình và tính năng vượt trội độc quyền hỗ trợ bởi trí tuệ nhân tạo.',
  },
  PRODUCTS: {
    SECTION_TITLE: 'SẢN PHẨM NỔI BẬT',
    OUT_OF_STOCK: 'Hết Hàng',
    IN_STOCK: 'Còn Hàng',
    LOW_STOCK: 'Sắp Hết',
  },
  AUTH: {
    LOGIN_TITLE: 'Chào mừng trở lại!',
    LOGIN_SUBTITLE: 'Đăng nhập tài khoản Sóc Mobile của bạn',
    LOGIN_BTN: 'Đăng Nhập',
    LOGGING_IN: 'Đang xử lý...',
    REGISTER_TITLE: 'Đăng ký thành viên',
    REGISTER_SUBTITLE: 'Trở thành thành viên Sóc Mobile để nhận nhiều ưu đãi',
    REGISTER_BTN: 'Đăng Ký Tài Khoản',
    REGISTERING: 'Đang đăng ký...',
    FULL_NAME: 'Họ và Tên *',
    EMAIL: 'Địa chỉ Email *',
    EMAIL_LOGIN: 'Địa chỉ Email',
    PHONE: 'Số điện thoại (10 chữ số)',
    PASSWORD: 'Mật khẩu *',
    PASSWORD_LOGIN: 'Mật khẩu',
    CONFIRM_PASSWORD: 'Nhập lại mật khẩu *',
    NO_ACCOUNT: 'Chưa có tài khoản?',
    ALREADY_ACCOUNT: 'Đã có tài khoản?',
    SIGNUP_NOW: 'Đăng ký ngay',
    SIGNIN_NOW: 'Đăng nhập ngay',
    BACK_TO_HOME: 'Quay về Trang chủ',
    ERROR_FILL_ALL: 'Vui lòng điền đầy đủ thông tin',
    ERROR_FILL_REQUIRED: 'Vui lòng điền đầy đủ các thông tin bắt buộc',
    ERROR_PASSWORD_MISMATCH: 'Mật khẩu nhập lại không trùng khớp',
    ERROR_PASSWORD_LENGTH: 'Mật khẩu phải chứa ít nhất 6 ký tự',
  },
  PRODUCT: {
    DEFAULT_VARIANT: 'Mặc định',
    INSTALLMENT_BADGE: 'Trả góp 0%',
    FAST_DELIVERY_BADGE: 'Giao 2h',
    REVIEWS: 'đánh giá',
    SOLD: 'Đã bán',
    CHOOSE_STORAGE: 'Chọn phiên bản dung lượng:',
    SPEC_TITLE: 'Thông số kỹ thuật:',
    SPEC_SCREEN: 'Màn hình',
    SPEC_CHIP: 'Vi xử lý (Chip)',
    SPEC_RAM: 'Bộ nhớ RAM',
    PROMOTION_TITLE: 'Khuyến mãi kèm theo:',
    COMPARE_TOOLTIP: 'So sánh cấu hình',
    FAVORITE_TOOLTIP: 'Thêm vào yêu thích',
    COMPARE_STATUS_ACTIVE: 'Đang so sánh',
    COMPARE_STATUS_INACTIVE: 'So sánh',
  },
  FILTERS: {
    CATEGORY_LABEL: 'Danh mục:',
    BRAND_LABEL: 'Hãng sản xuất:',
    NEED_LABEL: 'Chọn theo nhu cầu:',
    ALL_NEEDS: 'Tất cả nhu cầu',
    ALL_BRANDS: 'Tất cả',
    NEED_PREMIUM: 'Flagship Cao Cấp',
    NEED_GAMING: 'Chơi Game/Cấu Hình',
    NEED_CAMERA: 'Chụp Ảnh Đẹp',
    NEED_BATTERY: 'Pin Trâu/Sạc Nhanh',
    CATEGORY_OTHER: 'Khác',
    CATEGORY_MOBILE: 'Điện thoại',
    CATEGORY_LAPTOP: 'Laptop',
    CATEGORY_TABLET: 'Máy tính bảng',
    CATEGORY_WATCH: 'Đồng hồ thông minh',
    CATEGORY_ACCESSORY: 'Phụ kiện',
  },
  HOMEPAGE: {
    EXCLUSIVE_TAG: 'Đặc Quyền Mua Sắm',
    SEE_DETAILS: 'Xem chi tiết',
    BUY_NOW_PROMO: 'Mua ngay',
    FLASH_SALE_TITLE: 'DEAL SỐC MỖI NGÀY',
    FLASH_SALE_END: 'KẾT THÚC TRONG',
    UPGRADE_TITLE: 'LÊN ĐỜI SIÊU PHẨM',
    INSTALLMENT_PROMO: 'Hỗ trợ trả góp 0%',
    PRICE_FROM: 'Chỉ từ 2,08tr/tháng',
    SHOP_NOW: 'Sắm Ngay',
    PRODUCT_LIST: 'DANH SÁCH',
    FOUND: 'Tìm thấy',
    PRODUCTS_SUFFIX: 'sản phẩm',
    EMPTY_TITLE: 'Không tìm thấy sản phẩm phù hợp',
    EMPTY_DESC: 'Vui lòng thử chọn lại hãng sản xuất hoặc nhu cầu sử dụng khác.',
    RESET_FILTERS: 'Thiết lập lại bộ lọc',
  },
  CART: {
    TITLE: 'Giỏ hàng của bạn',
    EMPTY_TITLE: 'Giỏ hàng trống',
    EMPTY_DESC: 'Bạn chưa thêm sản phẩm nào vào giỏ hàng.',
    CONTINUE_SHOPPING: 'Tiếp tục mua sắm',
    PRODUCT_NAME: 'Sản phẩm',
    PRICE: 'Đơn giá',
    QUANTITY: 'Số lượng',
    TOTAL_ITEM_PRICE: 'Thành tiền',
    ORDER_SUMMARY: 'Thông tin đơn hàng',
    TEMP_PRICE: 'Tạm tính',
    SHIPPING_FEE: 'Phí vận chuyển',
    SHIPPING_FREE: 'Miễn phí',
    DISCOUNT: 'Giảm giá',
    FINAL_TOTAL: 'Tổng thanh toán',
    CHECKOUT_BTN: 'Tiến hành đặt hàng',
    APPLY_VOUCHER_PLACEHOLDER: 'Nhập mã giảm giá (GIAM50, SOC2K)',
    APPLY_VOUCHER_BTN: 'Áp dụng',
    VOUCHER_SUCCESS: 'Đã áp dụng mã giảm giá thành công!',
    VOUCHER_INVALID: 'Mã giảm giá không hợp lệ',
  },
  CHECKOUT: {
    TITLE: 'Thanh toán đơn hàng',
    SHIPPING_SECTION: 'Thông tin nhận hàng',
    FULL_NAME: 'Họ và tên người nhận *',
    PHONE_NUMBER: 'Số điện thoại liên hệ *',
    ADDRESS: 'Địa chỉ giao hàng chi tiết *',
    CITY_SELECT: 'Tỉnh / Thành phố *',
    CHOOSE_CITY: '-- Chọn Tỉnh/Thành phố --',
    PAYMENT_SECTION: 'Phương thức thanh toán',
    PAYMENT_COD: 'Thanh toán khi nhận hàng (COD)',
    PAYMENT_QR: 'Chuyển khoản ngân hàng qua mã QR (VietQR)',
    PAYMENT_DEPOSIT_5: 'Đặt cọc 5% giữ máy trước',
    PAYMENT_PAY_AT_STORE: 'Thanh toán 100% tại Cửa hàng (Showroom)',
    FULFILLMENT_HOME: 'Giao hàng tận nơi',
    FULFILLMENT_HOME_SUB: 'Hỏa tốc trong 2 giờ',
    FULFILLMENT_STORE: 'Đến Showroom trải nghiệm',
    FULFILLMENT_STORE_SUB: 'Cọc 5% giữ máy hoặc Thanh toán sau',
    SELECT_SHOWROOM: 'Chọn Showroom tiếp đón bạn',
    SELECT_APPOINTMENT_TIME: 'Chọn thời gian bạn sẽ đến cửa hàng',
    ORDER_SUMMARY: 'Đơn hàng của bạn',
    PLACE_ORDER_BTN: 'Xác nhận đặt hàng',
    CONFIRM_DEPOSIT_BTN: 'Xác nhận Đặt cọc 5%',
    QR_MODAL_TITLE: 'Thanh toán qua ngân hàng (VietQR)',
    QR_DEPOSIT_MODAL_TITLE: 'Quét mã Đặt cọc 5% Giữ máy',
    QR_INSTRUCTIONS: 'Vui lòng mở ứng dụng ngân hàng và quét mã QR dưới đây để thực hiện thanh toán chuyển khoản nhanh 24/7.',
    QR_BANK: 'Ngân hàng',
    QR_ACC_NO: 'Số tài khoản',
    QR_ACC_NAME: 'Chủ tài khoản',
    QR_AMOUNT: 'Số tiền chuyển khoản',
    QR_DEPOSIT_AMOUNT: 'Số tiền Cọc 5%',
    QR_CONTENT: 'Nội dung chuyển khoản',
    QR_CONFIRM_BTN: 'Tôi đã chuyển khoản thành công',
    QR_DEPOSIT_CONFIRM_BTN: 'Tôi đã chuyển khoản Cọc 5%',
    QR_CANCEL_BTN: 'Hủy giao dịch',
    QR_TIMER_ALERT: 'Hệ thống sẽ tự động xác nhận sau khi nhận được tiền...',
    ORDER_SUCCESS_TITLE: 'Đặt hàng thành công!',
    DEPOSIT_SUCCESS_TITLE: 'ĐẶT CỌC 5% GIỮ MÁY THÀNH CÔNG!',
    DEPOSIT_SUCCESS_DESC: 'Showroom đã giữ máy đúng màu sắc và phiên bản cho bạn trong 48h. Vui lòng đến Showroom để trải nghiệm và thanh toán số tiền còn lại.',
    ORDER_SUCCESS_DESC: 'Cảm ơn bạn đã mua sắm tại Sóc Mobile. Đơn hàng của bạn đang được xử lý.',
    ORDER_CODE: 'Mã đơn hàng',
    BACK_TO_HOME: 'Quay về trang chủ',
    TRACK_THIS_ORDER: 'Tra cứu đơn hàng này',
    ERROR_MISSING_ADDRESS: 'Vui lòng nhập địa chỉ và thành phố nhận hàng.',
    DEFAULT_CUSTOMER_NAME: 'Khách hàng',
    DEFAULT_PHONE: '0987654321',
  },
  COMPARE: {
    TITLE: 'So sánh sản phẩm',
    SELECT_PRODUCT: 'Chọn sản phẩm',
    CHOOSE_DIFFERENT: 'Hãy chọn 2 sản phẩm cùng loại điện thoại để so sánh',
    AI_ADVICE_TITLE: 'Trợ lý Tư vấn AI (LangChain)',
    AI_ADVICE_DESC: 'Nhập nhu cầu sử dụng của bạn (ví dụ: chơi game, chụp ảnh, học tập,...) để AI tư vấn so sánh chi tiết hai sản phẩm này.',
    AI_INPUT_PLACEHOLDER: 'Ví dụ: Tôi cần điện thoại chơi game tốt, sạc nhanh và pin trâu...',
    AI_BUTTON: 'Nhận tư vấn từ AI',
    AI_THINKING: 'AI đang phân tích và soạn thảo phản hồi...',
    AI_RESPONSE_HEADER: 'Phản hồi từ Trợ lý Sóc Mobile AI:',
    AI_DEFAULT_RESPONSE: 'Vui lòng chọn 2 sản phẩm và nhập nhu cầu để bắt đầu tư vấn.',
    COMPARE_BAR_TITLE: 'So sánh sản phẩm',
    COMPARE_BAR_BTN: 'So sánh ngay',
    COMPARE_BAR_CLEAR: 'Xóa tất cả',
  },
  CHATBOT: {
    TITLE: 'Sóc Mobile AI Assistant',
    WELCOME: 'Xin chào! Mình là Sóc Mobile AI Assistant. Mình có thể giúp gì cho bạn hôm nay? (Ví dụ: tìm điện thoại chụp ảnh đẹp, tư vấn mua trả góp, chính sách bảo hành,...)',
    INPUT_PLACEHOLDER: 'Hỏi Sóc AI điều gì đó...',
    SEND_BTN: 'Gửi',
    SUGGESTION_TITLE: 'Gợi ý câu hỏi:',
    SUGGESTION_1: 'Tư vấn điện thoại chơi game tầm giá 10 triệu',
    SUGGESTION_2: 'Chính sách trả góp 0% tại Sóc Mobile như thế nào?',
    SUGGESTION_3: 'Điện thoại nào chụp ảnh đẹp nhất hiện nay?',
  },
};

